/* M: Later on, get this info from the database.
*/

export const ProductData = [
    {
        id: 1,
        name: "Doritos Hot",
        image: require("../../images/food.png"),
        description: "desc 1",
        brand: "Doritos",
        category: "Snacks",
        rating: 0,
        numReviews: 0,
        price: 3.99,
        countInStock: 10,
    },
    {
        id: 2,
        name: "Doritos Chill",
        image: require("../../images/food.png"),
        description: "desc 2",
        brand: "Doritos",
        category: "Snacks",
        rating: 0,
        numReviews: 0,
        price: 4.99,
        countInStock: 10,
    },
    {
        id: 3,
        name: "Doritos Classic",
        image: require("../../images/food.png"),
        description: "desc 3",
        brand: "Doritos",
        category: "Snacks",
        rating: 0,
        numReviews: 0,
        price: 4.99,
        countInStock: 10,
    },
    {
        id: 4,
        name: "AriZona White Tea",
        image: require("../../images/food.png"),
        description: "desc 5",
        brand: "AriZona",
        category: "Drinks",
        rating: 0,
        numReviews: 0,
        price: 5.99,
        countInStock: 10,
    },
    {
        id: 5,
        name: "AriZona Watermelon",
        image: require("../../images/food.png"),
        description: "desc 5",
        brand: "AriZona",
        category: "Drinks",
        rating: 0,
        numReviews: 0,
        price: 5.99,
        countInStock: 10,
    },
    {
        id: 6,
        name: "Sprite Zero",
        image: require("../../images/food.png"),
        description: "desc 6",
        brand: "Sprite",
        category: "Drinks",
        rating: 0,
        numReviews: 0,
        price: 4.99,
        countInStock: 10,
    }
]